In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]],dtype=np.int8)
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
# get a specific element  [r,c]
print(a[1,-2])

5


In [4]:
# get a specific row 
print(a[0,:])

[1 2 3]


In [5]:
# get a specific column
print(a[:,1])


[2 5]


In [7]:
# getting a fancy
print(a[0,0:3:2])

[1 3]


In [8]:
a[0,:]=0
print(a)

[[0 0 0]
 [4 5 6]]


In [10]:
## Three d examples
three3d= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(three3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
# Get specific element
print(three3d[0,0,0])

1


In [12]:
# replace 
three3d[:,0,:]


array([[1, 2],
       [5, 6]])