In [9]:
import numpy as np


In [5]:
## all zeros matrix
np.zeros((2,2,2,))


array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [6]:
## all ones
np.ones((1,1,1))

array([[[1.]]])

In [7]:
# full
np.full((2,2),100)

array([[100, 100],
       [100, 100]])

In [12]:
# random
np.random.rand(3,2)

array([[0.147907  , 0.49891742],
       [0.19074551, 0.58080884],
       [0.39417667, 0.60013052]])

1. Тэгэхлээр бид юу сурсан вэ ? 
zeros ,ones, full ,rand, identity , full_like , repeat 
2. Бид цаашид яах вэ ? 
Бид эдгээрээс ямар арга техник ашиглаж болох вээ гэдгийг харах ажээ .