In [1]:
import numpy as np

In [5]:
b=np.array([1,2,3])
a=b.copy()
a[0]=3
print(a)
print(b)

[3 2 3]
[1 2 3]


In [6]:
## element wise
a=np.array([8,9,3])

In [8]:
np.cos(a)


array([-0.14550003, -0.91113026, -0.9899925 ])

In [11]:
## linear algebra
a=np.ones((2,4))
b=np.full((4,2),9)
np.max(b,axis=1)

array([9, 9, 9, 9])

In [34]:
## reorganizing arrays
a=np.full((3,3),1)
b=a.reshape((1,9))
gen=np.genfromtxt('data.txt',delimiter=',')
gen=gen.reshape((2,7))
gen=gen.astype('int32')
print(gen.sum())

10322


In [56]:
gen.size
oneDimension=gen.reshape((1,14))
print(oneDimension)
oneDimension[oneDimension>0]

[[   1    2    2    3    4    4    5    1 5123    1 5123    1   51    1]]


array([   1,    2,    2,    3,    4,    4,    5,    1, 5123,    1, 5123,
          1,   51,    1], dtype=int32)